// <auto-generated />
namespace Prac_Contact_Directory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IntialIgnoreChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialIgnoreChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202211160502207_Intial-IgnoreChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
